# Generated by Django 5.2.6 on 2025-12-22 12:01

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/categories/', verbose_name='Category Image (250X250px)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('order', models.IntegerField(blank=True, default=None, null=True, verbose_name='Order')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='cms.blogcategory', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Blog Title')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Short Description')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Featured Image (800X400px)')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='Published Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('view_counter', models.IntegerField(default=0, verbose_name='Views')),
                ('order', models.IntegerField(default=0, null=True, verbose_name='Order')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='draft', max_length=10, verbose_name='Status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Post')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Title (SEO)')),
                ('meta_description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Meta Description (SEO)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='Select main category (parent category)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='cms.blogcategory', verbose_name='Blog Category')),
                ('subcategory', models.ForeignKey(blank=True, help_text='Select subcategory (child category)', limit_choices_to={'parent__isnull': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_blogs', to='cms.blogcategory', verbose_name='Blog Subcategory')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-post_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CMS',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pagename', models.CharField(default=None, max_length=150, null=True, verbose_name='Page Name')),
                ('Content', ckeditor_uploader.fields.RichTextUploadingField(default='No News', null=True, verbose_name='Long Discretion')),
                ('pageimage', models.ImageField(blank=True, null=True, upload_to='cms/', verbose_name='Page Image (1280X220px)')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Slug')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viewcounter', models.IntegerField(default=0, null=True, verbose_name='Views')),
                ('post_status', models.IntegerField(default=100, null=True, verbose_name='Counter')),
                ('order', models.IntegerField(default=5, null=True, verbose_name='Order')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Management System',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='profile_setting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('logo_light', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logo Light (500X100px)')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logo Dark (500X100px)')),
                ('footer_img', models.ImageField(blank=True, null=True, upload_to='profile_image/', verbose_name='Footer Image (1920X365px)')),
                ('body_img', models.ImageField(blank=True, null=True, upload_to='profile_image/', verbose_name='Body Image (1920X365px)')),
                ('background_theme_light', models.CharField(blank=True, default='#FFFFFF', help_text='Light Background', max_length=7, null=True, verbose_name='background Theme Light')),
                ('background_theme_dark', models.CharField(blank=True, default='#000000', help_text='Dark Background', max_length=7, null=True, verbose_name='background Theme Dark')),
                ('container_background', models.CharField(blank=True, default='#fcf8e7', help_text='container background in body', max_length=7, null=True, verbose_name='container background')),
                ('items_background', models.CharField(blank=True, default='#FFFFFF', help_text='items background in body', max_length=7, null=True, verbose_name='Items background')),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('phone_number1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number 1')),
                ('phone_number2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number 2')),
                ('facbook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Linkedin')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='Youtube')),
                ('main_office_address', models.TextField(blank=True, max_length=200, null=True, verbose_name='Main Office Address')),
                ('branch_office_address', models.TextField(blank=True, max_length=255, null=True, verbose_name='Branch Office Address')),
                ('google_map', models.TextField(blank=True, help_text='Embed Code', null=True, verbose_name='Google Map')),
                ('copyright', models.CharField(blank=True, max_length=255, null=True, verbose_name='Copyright')),
                ('establish_at', models.DateField(blank=True, null=True, verbose_name='Establish At')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Setting',
            },
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sliderimage', models.ImageField(blank=True, null=True, upload_to='slider/', verbose_name='Slider Image (1400X520px)')),
                ('ad_title', models.CharField(blank=True, help_text='Title for the slider advertisement', max_length=200, null=True, verbose_name='Ad Title')),
                ('ad_description', models.TextField(blank=True, help_text='Description for the slider advertisement', null=True, verbose_name='Ad Description')),
                ('deal_type', models.CharField(blank=True, choices=[('hot_deals', 'Hot Deal'), ('summer_deal', 'Summer Deal'), ('best_sale_product', 'Best Sale Product'), ('high_demand_product', 'High Demand Product'), ('others', 'Others')], help_text='Select the type of deal for this slider ad', max_length=50, null=True, verbose_name='Deal Type')),
                ('ad_start_date', models.DateField(blank=True, help_text='Start date for when this ad should be displayed', null=True, verbose_name='Ad Start Date')),
                ('ad_end_date', models.DateField(blank=True, help_text='End date for when this ad should stop being displayed', null=True, verbose_name='Ad End Date')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Slug')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=5, null=True, verbose_name='Order')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
