# Generated by Django 5.2.6 on 2025-12-22 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Select a product to link to this slider ad (160 character only)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='slider',
            name='slidercat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.category', verbose_name='Select Category'),
        ),
    ]
