# Generated by Django 5.2.6 on 2025-12-10 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/categories/', verbose_name='Category Image (250X250px)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('order', models.IntegerField(blank=True, default=None, null=True, verbose_name='Order')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='cms.blogcategory', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select main category (parent category)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='cms.blogcategory', verbose_name='Blog Category'),
        ),
        migrations.AddField(
            model_name='blog',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Select subcategory (child category)', limit_choices_to={'parent__isnull': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_blogs', to='cms.blogcategory', verbose_name='Blog Subcategory'),
        ),
    ]
