# Generated by Django 5.2.6 on 2025-12-14 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_blogcategory_blog_category_blog_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='ad_description',
            field=models.TextField(blank=True, help_text='Description for the slider advertisement', null=True, verbose_name='Ad Description'),
        ),
        migrations.AddField(
            model_name='slider',
            name='ad_title',
            field=models.CharField(blank=True, help_text='Title for the slider advertisement', max_length=200, null=True, verbose_name='Ad Title'),
        ),
        migrations.AddField(
            model_name='slider',
            name='deal_type',
            field=models.CharField(blank=True, choices=[('summer_deal', 'Summer Deal'), ('best_sale_product', 'Best Sale Product'), ('high_demand_product', 'High Demand Product'), ('others', 'Others')], help_text='Select the type of deal for this slider ad', max_length=50, null=True, verbose_name='Deal Type'),
        ),
        migrations.AddField(
            model_name='slider',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Select a product to link to this slider ad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.product', verbose_name='Product'),
        ),
    ]
