# Generated by Django 5.2.6 on 2025-12-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_setting',
            name='logo_dark',
            field=models.FileField(blank=True, help_text='Accepts SVG, PNG, JPG files', null=True, upload_to='logo/', verbose_name='Logo Dark (SVG, PNG, JPG - 500X100px)'),
        ),
        migrations.AlterField(
            model_name='profile_setting',
            name='logo_light',
            field=models.FileField(blank=True, help_text='Accepts SVG, PNG, JPG files', null=True, upload_to='logo/', verbose_name='Logo Light (SVG, PNG, JPG - 500X100px)'),
        ),
    ]
