# Generated by Django 5.2.6 on 2026-01-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_profile_setting_logo_dark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slidervideo',
            field=models.FileField(blank=True, help_text='Upload a video file (mp4, webm, ogg) OR use image above', null=True, upload_to='slider/videos/', verbose_name='Slider Video'),
        ),
        migrations.AddField(
            model_name='slider',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional: YouTube or Vimeo video URL', max_length=500, null=True, verbose_name='Video URL (YouTube/Vimeo)'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='sliderimage',
            field=models.ImageField(blank=True, help_text='Upload an image OR a video (not both)', null=True, upload_to='slider/', verbose_name='Slider Image (1400X520px)'),
        ),
    ]
