# Generated by Django 5.2.6 on 2025-12-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_slider_ad_description_slider_ad_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='ad_end_date',
            field=models.DateField(blank=True, help_text='End date for when this ad should stop being displayed', null=True, verbose_name='Ad End Date'),
        ),
        migrations.AddField(
            model_name='slider',
            name='ad_start_date',
            field=models.DateField(blank=True, help_text='Start date for when this ad should be displayed', null=True, verbose_name='Ad Start Date'),
        ),
    ]

