# Generated by Django 5.2.6 on 2025-12-14 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_slider_ad_start_date_slider_ad_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='des',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title',
        ),
    ]

