# Generated by Django 5.2.6 on 2026-01-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_slider_slidervideo_slider_video_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['order'], 'verbose_name': 'Slider', 'verbose_name_plural': 'Sliders'},
        ),
        migrations.AlterField(
            model_name='slider',
            name='deal_type',
            field=models.CharField(blank=True, choices=[('hot_deals', 'Hot Deal(Main slider)'), ('best_summer_deal', 'Best Summer Deal'), ('best_sale_product', 'Best Sale Product'), ('high_demand_product', 'High Demand Product'), ('others', 'Others')], help_text='Select the type of deal for this slider ad', max_length=50, null=True, verbose_name='Deal Type'),
        ),
    ]
