# Generated by Django 5.2.6 on 2026-01-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_slider_options_alter_slider_deal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags (e.g., Cosmetics, Makeup, Skincare)', max_length=500, null=True, verbose_name='Tags'),
        ),
    ]
