# Generated by Django 5.2.6 on 2026-01-19 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_remove_slider_title_remove_slider_des'),
        ('cms', '0006_blog_tags'),
    ]

    operations = [
    ]
