# Generated by Django 5.2.6 on 2026-01-20 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_merge_20260119_0927'),
        ('ecommerce', '0024_merge_20260119_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slider',
            name='deal_type',
            field=models.CharField(blank=True, choices=[('hot_deals', 'Hot Deal(Main slider)'), ('best_summer_deal', 'Best Summer Deal'), ('best_sale_product', 'Best Sale Product'), ('high_demand_product', 'High Demand Product'), ('others', 'Others')], help_text='Select the type of deal for this slider ad', max_length=50, null=True, verbose_name='Deal Type'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Select a product to link to this slider ad (160 character only)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.product', verbose_name='Product'),
        ),
    ]
