# Generated by Django 5.2.6 on 2025-12-22 12:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='brands/%Y/%m/%d', verbose_name='Brand Image')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remark/Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('order', models.IntegerField(blank=True, default=None, null=True, verbose_name='Order')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'main_brand',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/%Y/%m/%d', verbose_name='Category Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('order', models.IntegerField(blank=True, default=None, null=True, verbose_name='Order')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'main_category',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'main_contactmessage',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('support', 'Support Staff')], default='customer', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.permission')),
            ],
            options={
                'db_table': 'main_customuser',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.customuser')),
            ],
            options={
                'db_table': 'main_order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(verbose_name='Key Points')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='MRP (INR)')),
                ('offerprice', models.DecimalField(decimal_places=2, default='00.00', max_digits=10, verbose_name='Offer Price (INR)')),
                ('stock', models.PositiveIntegerField()),
                ('quantity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qty')),
                ('unit', models.CharField(blank=True, choices=[('ml', 'ml'), ('l', 'L'), ('g', 'g'), ('kg', 'kg'), ('pcs', 'pcs'), ('pieces', 'pieces'), ('m', 'm'), ('cm', 'cm'), ('inch', 'inch'), ('ft', 'ft'), ('oz', 'oz'), ('lb', 'lb')], max_length=50, null=True, verbose_name='Unit')),
                ('is_sku_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU Code')),
                ('color_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='Color Code')),
                ('popular', models.BooleanField(default=True)),
                ('latest', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=True)),
                ('available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('order', models.IntegerField(blank=True, default=None, null=True, verbose_name='Order')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='ecommerce.brand', verbose_name='Brand')),
            ],
            options={
                'db_table': 'main_product',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecommerce.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='ecommerce.product')),
            ],
            options={
                'db_table': 'main_orderitem',
            },
        ),
        migrations.CreateModel(
            name='ProductDetailSection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ecommerce.product')),
            ],
            options={
                'db_table': 'main_productdetailsection',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10, verbose_name='Media Type')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Upload image or video file (for video, max 2MB)', null=True, upload_to='products/%Y/%m/%d')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ecommerce.product')),
            ],
            options={
                'db_table': 'main_productimage',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='subcategories/%Y/%m/%d', verbose_name='SubCategory Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('order', models.IntegerField(blank=True, default=None, null=True, verbose_name='Order')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='ecommerce.category', verbose_name='Main Category')),
            ],
            options={
                'verbose_name_plural': 'SubCategories',
                'db_table': 'main_subcategory',
                'ordering': ['category__order', 'category__name', 'order', 'name'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ecommerce.subcategory', verbose_name='SubCategory'),
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='ecommerce.customuser')),
            ],
            options={
                'db_table': 'main_useraddress',
                'ordering': ['-is_default', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('quantity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qty')),
                ('unit', models.CharField(blank=True, choices=[('ml', 'ml'), ('l', 'L'), ('g', 'g'), ('kg', 'kg'), ('pcs', 'pcs'), ('pieces', 'pieces'), ('m', 'm'), ('cm', 'cm'), ('inch', 'inch'), ('ft', 'ft'), ('oz', 'oz'), ('lb', 'lb')], max_length=50, null=True, verbose_name='Unit')),
                ('is_sku_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU Code')),
                ('color_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='Color Code')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug')),
                ('price_modifier', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Price +/-')),
                ('offerprice', models.DecimalField(blank=True, decimal_places=2, default='00.00', max_digits=10, null=True, verbose_name='Offer Price (INR)')),
                ('stock', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Stock')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='ecommerce.product')),
            ],
            options={
                'db_table': 'main_productvariation',
                'unique_together': {('product', 'name', 'quantity')},
            },
        ),
    ]
