# Generated by Django 5.2.6 on 2025-12-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
