# Generated by cleanup script

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_remove_product_image_productimage'),
    ]

    operations = [
    ]
