# Generated by cleanup script

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_product_short_description'),
    ]

    operations = [
    ]
