# Generated by cleanup script

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_productvariation_unique_together'),
    ]

    operations = [
    ]
