# Generated by cleanup script

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_category_parent'),
    ]

    operations = [
    ]
