# Generated by Django 5.2.6 on 2025-12-28 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_orderitem_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount Amount'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='e.g., SAVE20', max_length=50, unique=True, verbose_name='Coupon Code')),
                ('discount_amount', models.IntegerField(default=10, help_text='Amount or Percentage', verbose_name='Discount Amount')),
                ('discount_type', models.CharField(choices=[('flat', 'Flat ₹'), ('percent', '%')], default='percent', max_length=10, verbose_name='Discount Type')),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0, help_text='E.g. Min Order 500', max_digits=10, verbose_name='Minimum Purchase Amount')),
                ('valid_from', models.DateTimeField(verbose_name='Valid From')),
                ('valid_to', models.DateTimeField(verbose_name='Valid To')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('usage_limit', models.IntegerField(default=100, help_text='Total times this coupon can be used', verbose_name='Usage Limit')),
                ('used_count', models.IntegerField(default=0, help_text='How many times this coupon has been used', verbose_name='Used Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('valid_categories', models.ManyToManyField(blank=True, help_text='If empty, coupon is valid for all categories', to='ecommerce.category', verbose_name='Valid Categories')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'db_table': 'main_coupon',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='ecommerce.coupon'),
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Used At')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='ecommerce.coupon', verbose_name='Coupon')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage', to='ecommerce.order', verbose_name='Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='ecommerce.customuser', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Coupon Usage',
                'verbose_name_plural': 'Coupon Usages',
                'db_table': 'main_couponusage',
                'ordering': ['-used_at'],
                'unique_together': {('user', 'coupon')},
            },
        ),
    ]
