# Generated by Django 5.2.6 on 2026-01-03 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_order_discount_total_coupon_order_coupon_couponusage'),
        ('ecommerce', '0007_payment'),
    ]

    operations = [
    ]
