# Generated by cleanup script

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_category_is_active_category_order_product_is_active_and_more'),
    ]

    operations = [
    ]
