# Generated by Django 5.2.6 on 2026-01-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_merge_20260103_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='valid_products',
            field=models.ManyToManyField(blank=True, help_text='If empty, coupon is valid for all products', to='ecommerce.product', verbose_name='Valid Products'),
        ),
    ]
