# Generated by Django 5.2.6 on 2026-01-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_coupon_valid_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupons',
            field=models.ManyToManyField(blank=True, related_name='orders_m2m', to='ecommerce.coupon'),
        ),
    ]
