# Generated by cleanup script

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_product_featured_product_latest_product_offerprice_and_more'),
    ]

    operations = [
    ]
