# Generated by cleanup script

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ecommerce', '0010_alter_product_category_alter_product_offerprice_and_more'),
    ]

    operations = [
    ]
