# Generated by Django 5.2.6 on 2026-01-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_order_coupons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(choices=[('MY_SUNDAY', 'My Sunday'), ('NEW_LAUNCH', 'New Launch'), ('HOT_PRODUCT', 'Hot Product'), ('DIWALI', 'Diwali Offer'), ('FLASH', 'Flash Sale'), ('CLEARANCE', 'Clearance Sale')], max_length=50, verbose_name='Offer Type / Badge')),
                ('page_position', models.CharField(choices=[('HOME_TOP', 'Homepage Top Banner'), ('HOME_MIDDLE', 'Homepage Middle Section'), ('HOME_BOTTOM', 'Homepage Bottom'), ('LISTING', 'Category / Listing Page'), ('PRODUCT', 'Product Detail Page')], max_length=50, verbose_name='Page Position')),
                ('offer_title', models.CharField(max_length=150, verbose_name='Offer Title')),
                ('offer_slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('offer_description', models.TextField(blank=True, null=True)),
                ('offer_image', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('meta_title', models.CharField(blank=True, max_length=160, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'offers',
                'ordering': ['-created_at'],
            },
        ),
    ]
