# Generated by cleanup script

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_alter_customuser_first_name_and_more'),
    ]

    operations = [
    ]
