# Generated by Django 5.2.6 on 2026-01-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_alter_offer_meta_fields_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='offer',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Display Order'),
        ),
    ]
