# Generated by cleanup script

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_brand_product_brand'),
    ]

    operations = [
    ]
