# Generated by cleanup script

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_brand_image_brand_remark'),
    ]

    operations = [
    ]
