# Generated by cleanup script

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_category_image_category_created_category_updated'),
    ]

    operations = [
    ]
