# Generated by Django 5.2.6 on 2025-12-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_alter_category_options_alter_category_order_and_more'),
    ]

    operations = [
        # Add fields only if they don't exist (handled by Django, but we'll use RunSQL for safety)
        migrations.RunSQL(
            """
            SET @dbname = DATABASE();
            SET @tablename = 'main_productvariation';
            SET @columnname = 'quantity';
            SET @preparedStatement = (SELECT IF(
              (
                SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
                WHERE
                  (table_name = @tablename)
                  AND (table_schema = @dbname)
                  AND (column_name = @columnname)
              ) > 0,
              'SELECT 1',
              CONCAT('ALTER TABLE ', @tablename, ' ADD COLUMN ', @columnname, ' VARCHAR(100) NULL')
            ));
            PREPARE alterIfNotExists FROM @preparedStatement;
            EXECUTE alterIfNotExists;
            DEALLOCATE PREPARE alterIfNotExists;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            SET @dbname = DATABASE();
            SET @tablename = 'main_productvariation';
            SET @columnname = 'unit';
            SET @preparedStatement = (SELECT IF(
              (
                SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
                WHERE
                  (table_name = @tablename)
                  AND (table_schema = @dbname)
                  AND (column_name = @columnname)
              ) > 0,
              'SELECT 1',
              CONCAT('ALTER TABLE ', @tablename, ' ADD COLUMN ', @columnname, ' VARCHAR(50) NULL')
            ));
            PREPARE alterIfNotExists FROM @preparedStatement;
            EXECUTE alterIfNotExists;
            DEALLOCATE PREPARE alterIfNotExists;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Copy data from value to quantity if quantity is empty
        migrations.RunSQL(
            "UPDATE main_productvariation SET quantity = value WHERE (quantity IS NULL OR quantity = '') AND value IS NOT NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Update field verbose names
        migrations.AlterField(
            model_name='productvariation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Variation Name'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='price_modifier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price Modifier'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock'),
        ),
        # Remove old value field
        migrations.RemoveField(
            model_name='productvariation',
            name='value',
        ),
        # Finally, update unique_together constraint
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('product', 'name', 'quantity')},
        ),
    ]
