# Generated by cleanup script

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_alter_category_options_alter_category_order_and_more'),
    ]

    operations = [
    ]
