# Generated by Django 5.2.6 on 2025-12-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_alter_productvariation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qty'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='offerprice',
            field=models.DecimalField(decimal_places=2, default='00.00', max_digits=10, verbose_name='Offer Price (INR)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='MRP (INR)'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='price_modifier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price +/-'),
        ),
    ]
