# Generated by cleanup script

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_update_app_label'),
    ]

    operations = [
    ]
