# Generated by Django 5.2.6 on 2025-12-14 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_update_app_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='ecommerce.category'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.customuser'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecommerce.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='ecommerce.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='ecommerce.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ecommerce.category'),
        ),
        migrations.AlterField(
            model_name='productdetailsection',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ecommerce.product'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='ecommerce.product'),
        ),
        migrations.AlterModelTable(
            name='brand',
            table='main_brand',
        ),
        migrations.AlterModelTable(
            name='category',
            table='main_category',
        ),
        migrations.AlterModelTable(
            name='contactmessage',
            table='main_contactmessage',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='main_customuser',
        ),
        migrations.AlterModelTable(
            name='order',
            table='main_order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='main_orderitem',
        ),
        migrations.AlterModelTable(
            name='product',
            table='main_product',
        ),
        migrations.AlterModelTable(
            name='productdetailsection',
            table='main_productdetailsection',
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='main_productimage',
        ),
        migrations.AlterModelTable(
            name='productvariation',
            table='main_productvariation',
        ),
    ]
