# Generated by cleanup script

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_alter_customuser_options_alter_category_parent_and_more'),
    ]

    operations = [
    ]
