# Generated by Django 5.2.6 on 2026-01-19 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_make_offer_image_required'),
        ('ecommerce', '0023_productvariation_is_sku_code_productvariation_color_code_alter_productvariation_unit'),
    ]

    operations = [
    ]
