# Generated by Django 5.2.6 on 2025-12-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
