# Generated by Django 5.1.1 on 2025-05-05 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productvariation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('product', 'name', 'value')},
        ),
    ]
