# Generated by Django 5.1.7 on 2025-05-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_productdetailsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=None, null=True, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.IntegerField(default=None, null=True, unique=True, verbose_name='Order'),
        ),
    ]
