# Generated by Django 5.1.7 on 2025-05-22 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_product_featured_product_latest_product_offerprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(limit_choices_to={'parent__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='offerprice',
            field=models.DecimalField(decimal_places=2, default='00.00', max_digits=10, verbose_name='Offer Price (AED)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='MRP (AED)'),
        ),
    ]
