# Generated by Django 5.2.6 on 2025-12-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brands/%Y/%m/%d', verbose_name='Brand Image'),
        ),
        migrations.AddField(
            model_name='brand',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Remark/Description'),
        ),
    ]
