"""
Django settings for mriigproject project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import mimetypes
from datetime import timedelta
from dotenv import load_dotenv

load_dotenv()  # Load environment variables from .env file

#AUTH_USER_MODEL = 'ecommerce.CustomUser'


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=z9lp(k@r2!-j)=0oa9t(v$ycks3i&((l$aa*2j=omw))#ksuj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
#ALLOWED_HOSTS = ['mriigg.com', 'www.mriigg.com']

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = True  # 👈 Allow all origins for dev

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    'ckeditor_uploader',
    'autoslug',
    'ecommerce.apps.EcommerceConfig',
    'cms',
    'api',
    'corsheaders',  # 👈 Added CORS headers
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # 👈 Added CORS Middleware (Must be before CommonMiddleware)
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mriigproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ecommerce.context_processors.cart_item_count',
                'ecommerce.context_processors.custom_user_context',  # ✅ add this line
                'ecommerce.context_processors.categories_context',  # ✅ add categories context
                'ecommerce.context_processors.profile_setting_context',  # ✅ add profile_setting context
                'ecommerce.context_processors.offers_context',  # ✅ add offers context

            ],
        },
    },
]

WSGI_APPLICATION = 'mriigproject.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'mriigdb.sqlite3',
#     }
# }

# Database Configuration - Auto-detect Local or Production
# Check if running on production server
import socket
IS_PRODUCTION = False

# Method 1: Check environment variables (primary method)
if os.getenv('DJANGO_ENV') == 'production' or os.getenv('ENVIRONMENT') == 'production':
    IS_PRODUCTION = True

# Method 2: Check if production DB credentials are set via environment variables
if not IS_PRODUCTION:
    db_user = os.getenv('DB_USER', '')
    db_name = os.getenv('DB_NAME', '')
    if db_user and 'tqjsimyv' in db_user:
        IS_PRODUCTION = True
    elif db_name and 'tqjsimyv' in db_name:
        IS_PRODUCTION = True

# Method 3: Check hostname
if not IS_PRODUCTION:
    try:
        hostname = socket.gethostname()
        if 'mriigg.com' in hostname or 'www.mriigg.com' in hostname or 'tqjsimyv' in hostname:
            IS_PRODUCTION = True
    except:
        pass

# Method 4: Check if DEBUG is False (production indicator)
if not IS_PRODUCTION and not DEBUG:
    IS_PRODUCTION = True

# Method 5: Check BASE_DIR path for production indicators
if not IS_PRODUCTION:
    try:
        base_dir_str = str(BASE_DIR)
        if 'tqjsimyv' in base_dir_str or 'mriigg.com' in base_dir_str or '/home/' in base_dir_str:
            # If we're in a production-like path, use production config
            IS_PRODUCTION = True
    except:
        pass

# Method 6: Final fallback - if DEBUG is False, assume production
if not IS_PRODUCTION and not DEBUG:
    IS_PRODUCTION = True

# Use environment variables if set, otherwise use defaults based on IS_PRODUCTION
if IS_PRODUCTION:
    # Production/Live Database Configuration
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME', 'tqjsimyv_mriiggdb'),
            'USER': os.getenv('DB_USER', 'tqjsimyv_mriigguser'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'f!_u-NOW[RF)RyZs'),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': os.getenv('DB_PORT', '3306'),
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'charset': 'utf8mb4',
            },
            'CONN_MAX_AGE': 600,  # Connection pooling - keep connections alive for 10 minutes
        }
    }
else:
    # Local/Development Database Configuration
    # But check if production DB credentials are provided via env vars
    db_user = os.getenv('DB_USER', '')
    db_name = os.getenv('DB_NAME', '')
    
    # If production credentials are provided, use them even if IS_PRODUCTION is False
    if db_user and 'tqjsimyv' in db_user:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.mysql',
                'NAME': os.getenv('DB_NAME', 'tqjsimyv_mriiggdb'),
                'USER': os.getenv('DB_USER', 'tqjsimyv_mriigguser'),
                'PASSWORD': os.getenv('DB_PASSWORD', 'f!_u-NOW[RF)RyZs'),
                'HOST': os.getenv('DB_HOST', '127.0.0.1'),
                'PORT': os.getenv('DB_PORT', '3306'),
                'OPTIONS': {
                    'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                    'charset': 'utf8mb4',
                },
                'CONN_MAX_AGE': 600,
            }
        }
    elif db_name and 'tqjsimyv' in db_name:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.mysql',
                'NAME': os.getenv('DB_NAME', 'tqjsimyv_mriiggdb'),
                'USER': os.getenv('DB_USER', 'tqjsimyv_mriigguser'),
                'PASSWORD': os.getenv('DB_PASSWORD', 'f!_u-NOW[RF)RyZs'),
                'HOST': os.getenv('DB_HOST', '127.0.0.1'),
                'PORT': os.getenv('DB_PORT', '3306'),
                'OPTIONS': {
                    'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                    'charset': 'utf8mb4',
                },
                'CONN_MAX_AGE': 600,
            }
        }
    else:
        # Local/Development Database Configuration
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.mysql',
                'NAME': os.getenv('DB_NAME', 'mrigg_live'),
                'USER': os.getenv('DB_USER', 'root'),
                'PASSWORD': os.getenv('DB_PASSWORD', ''),
                'HOST': os.getenv('DB_HOST', '127.0.0.1'),
                'PORT': os.getenv('DB_PORT', '3306'),
                'OPTIONS': {
                    'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                    'charset': 'utf8mb4',
                },
                'CONN_MAX_AGE': 600,  # Connection pooling - keep connections alive for 10 minutes
            }
        }

# Gokwik Payment Configuration
GOKWIK_MERCHANT_ID = os.getenv('GOKWIK_MERCHANT_ID')
GOKWIK_APP_ID = os.getenv('GOKWIK_APP_ID')
GOKWIK_APP_SECRET = os.getenv('GOKWIK_APP_SECRET')
GOKWIK_BASE_URL = os.getenv('GOKWIK_BASE_URL', 'https://sandbox-api.gokwik.co')

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CKEditor Settings
CKEDITOR_BASEPATH='/static/ckeditor/ckeditor/'
CKEDITOR_UPLOAD_PATH='upload/'
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar':'full',
        'removePlugins':'exportpdf',
        'extraPlugins': ','.join(
            [
                'codesnippet','widget','html5video','youtube',
            ]),
    },
}

mimetypes.add_type("image/webp", ".webp", True)
mimetypes.add_type("image/svg+xml", ".svg", True)

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True
LOGIN_URL = '/login/'


# LOGIN_REDIRECT_URL = '/'
# LOGOUT_REDIRECT_URL = '/login/'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# For production - where collected static files will be stored
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Ensure staticfiles directory exists
os.makedirs(STATIC_ROOT, exist_ok=True)

# Use WhiteNoise for production, but allow staticfiles to work in development too
if not DEBUG:
    
    STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"
else:
  
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging Configuration for Debugging
# Set to False if you don't want to see SQL queries in console
ENABLE_SQL_LOGGING = True  # Change to False to disable SQL query logging

if ENABLE_SQL_LOGGING and DEBUG:
    LOGGING = {
        'version': 1,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'loggers': {
            'django.db.backends': {
                'handlers': ['console'],
                'level': 'DEBUG',
            },
        },
    }
else:
    # Disable SQL query logging
    LOGGING = {
        'version': 1,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'loggers': {
            'django.db.backends': {
                'handlers': ['console'],
                'level': 'WARNING',  # Only show warnings and errors
            },
        },
    }




REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api.authentication.CustomUserJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=6),   # 👈 increase
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,

    'AUTH_HEADER_TYPES': ('Bearer',),
}


# ================= RAZORPAY CONFIGURATION =================
RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID", "rzp_live_S6CFwxNscpTr8p")
RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET","GE7CZ2pH3alP7KdBjmCXFj6w")


# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)